language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test_requirements.txt --use-mirrors
script:
  - coverage run `which nosetests` hascore tests
after_success:
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
